# Generated by Django 4.0.4 on 2022-05-30 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_remove_profile_id_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
    ]
