# Generated by Django 4.0.4 on 2022-06-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_rename_user_profile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='socialmedia',
            new_name='socialmed',
        ),
    ]
