# Generated by Django 4.0.4 on 2022-06-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0004_rename_socialmedia_profile_socialmed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='socialmed',
            new_name='socialmedia',
        ),
    ]
