# Generated by Django 4.0.4 on 2022-06-06 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_rename_socialmed_profile_socialmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='socialmedia',
        ),
    ]
